### PR TITLE
NFT changes

### PR DESCRIPTION
**Pull request by WyattMufson**
- Merged in master
- `tokensOfOwner` is now `tokensOf`
- `tokensOf` returns an enumerator of token objects
- Removed `tokens`
- `balanceOf` can take either one or two arguments (either returns the balance of all tokens for the owner, or the amount of a specific token - for divisible tokens)
- Added `properties` method to get on-chain immutable properties

Changes for the conversation in https://github.com/neo-project/proposals/pull/41. Does not currently fix the issue with enumerators.

### CODE REVIEW

**Comment by WyattMufson** [comment]
@hal0x2328 this should make most of the changes we wanted. The only thing to determine is how we want to handle enumerators for `tokensOf` and `ownerOf`. Do we want to use an array or something like the DynamicList structure?

**Comment by hal0x2328** [comment]
I thought we were just going to stick with returning the enumerator object since it is the most efficient and simplest way to return a large list. My only question was - what is in the enumerator object - if it's just a token ID that's not very useful because you have to do several sub-queries to get the URI, properties, etc.

I would rather see enumerator values that contain a serialized token object containing `id`, `uri`, `properties`, `owner`, and `approved` (along with any other dApp-specific optional fields), so that the dApp can get all the information it needs to build a useful list with a single RPC query and iterator script.

**Comment by WyattMufson** [comment]
Yeah that would work. Is there a limit to how many objects the enumerator can store?

**Comment by hal0x2328** [comment]
No limits that I know of - it's literally just going to be returning the enumerator that is created by the LevelDB `Storage.Find` code - so theoretically you should be able to enumerate every matching prefix in the entire LevelDB contract storage no matter how large it grows.

**Comment by WyattMufson** [comment]
So I'll change it so that `tokensOf` returns an enumerator of token objects, with all of the required fields.

**Comment by WyattMufson** [comment]
@hal0x2328 should be good to go now

I didn't have it return the owner as part of the token since `tokensOf` already takes the owner as an argument so it'd be known already.

**Pull request merged**
